### ISSUE TITLE
✨ 방문일정 상세 조회 시 예상 인원 반환하도록 변경

### ISSUE THREAD

**Issue by uwoobeat** [FISOLUTION/fingerprint-backend#28]
## 📌 Description
- 방문일정 상세 조회 시 현장요원 사진을 볼 수 있다.
- 현재는, 방문일정 상세 조회 API가 현장요원 이름, 프로필 사진, 방문일시를 반환하게 되어 있는데,
- 앞으로, 방문일정 상세 조회 API는 현장요원 이름, 프로필 사진, 예상 인원을 반환한다.
- 포함하는 이슈 : ref #35 

## 📝 To-do
- [x]  `AgentDto`의 `profileUrl` 필드에 processImage로 찾아온 s3 이미지 링크 넣어주기
- [x] `ResponseDto`에 예상 인원 필드 추가
- [x] agent 도메인에 이미지 필드 추가
- [x] schedule 도메인에 예상 인원 필드 추가
- [x] s3에 현장요원 사진 업로드
- [x] agent db에 사진 링크 저장

![image](https://github.com/FISOLUTION/fingerprint-backend/assets/83302344/5e93a68e-b904-4014-a6b7-3d2fba18f31a)
