### ISSUE TITLE
✨ JWT 토큰 서버 구축

### ISSUE THREAD

**Issue by ChooSeoyeon** [FISOLUTION/fingerprint-backend#5]
## 📌 Description
- JWT 토큰 서버를 구축하고 관련한 개발 환경을 조성한다.

## 📝 To-do
- [x] JWT 토큰 서버 구축
- [x] 토큰 서버 테스트용 API 구현
    - [x] 회원 정보 조회 API
    - [x] 로그인 API
    - [x] 회원가입 API
